### ISSUE TITLE
How to use on a PIL image or Tensor?

### ISSUE THREAD

**Issue by JemiloII** [nagadomi/nunif#68] opened 2023-11-15 08:31 UTC
I want to integrate this into my stable diffusion app using the diffusers library. However, I am running into the issue where it wants a directory of images. I don't want to upscale a directory, nor do I want to give it a path to an image, but rather a PIL file so that while I am generating, I can chose to upscale/denoise then. I really like how Waifu2x denoises, so I want to add the denoising by default.

**Comment by nagadomi** [comment] 2023-11-15 09:23
You can use torch.hub interface.
https://github.com/nagadomi/nunif/blob/master/waifu2x/docs/python_api.md
At first use, code and pretrained models are loaded from this github repo.
If you want to bundle freezed code and pretrained models, directly import `waifu2x/hub.py`.
```python
import sys
sys.path.append("./nunif")
from waifu2x.hub import waifu2x

model = waifu2x(model_type="art").cuda()
```

**Comment by JemiloII** [comment] 2023-11-15 20:57
thanks I appreciate this. Another question.

So if I do `method=none`, it loads all models so I can later just call

model.set_mode(method, noise_level) to get the model I want while leaving the rest in memory?
Also, if I choose `scale` instead of `noise`, it will still denoise if the noise level is 0-3?

**Comment by JemiloII** [comment] 2023-11-15 21:05
Oh I found the other model types in ./hub.py

METHODS = [
    "noise", "scale", "noise_scale",
    "scale2x", "noise_scale2x",
    "scale4x", "noise_scale4x"
]

**Comment by nagadomi** [comment] 2023-11-15 22:25
When method=None, all the following models are loaded and each model is kept in GPU memory.
- 1x denoise 0-3
- 2x, 2x + denoise 0-3
- 4x, 4x + denoise 0-3 (if available)

>Also, if I choose scale instead of noise, it will still denoise if the noise level is 0-3?

Yes. 
- `method="scale", noise_level=-1` :  2x no denoising
- `method="scale", noise_level=2` : 2x + denoising level 2
- `method="noise_scale", noise_level=2` : 2x + denoising level 2 (same as above, just an alias, but noise_level=-1 cannot be specified) 

Internally, `method="scale", noise_level=2` is mapped to `method="noise_scale", noise_level=2`.
https://github.com/nagadomi/nunif/blob/b5dc08f1fa85ad39449a8859d03c84edddf49b66/waifu2x/hub.py#L118-L130

**Comment by nagadomi** [comment] 2023-11-15 22:41
I am not using this interface myself, so if you have any problems or requests, let me know.

**Comment by nagadomi** [comment] 2023-11-16 19:19
I fixed the error when using method,noise_level argument instead of set_mode. https://github.com/nagadomi/nunif/commit/ffb933a3fc31c619aaa4cd32a6c93536065015ff
Also, added GPU memory release/reload example 
https://github.com/nagadomi/nunif/blob/d30888b35571667a9a38654a0251da8286cd5fa2/waifu2x/hub.py#L200-L225

**Comment by JemiloII** [comment] 2023-11-16 21:50
So I switched to dev branch, so far the upscaling works but it is blurry compared to https://waifu2x.udp.jp/index.html.

Initial Image that gets generated and passed as a PIL image. No image is saved to disk before reaching Waifu2x
![2023-11-16_12-51-15](https://github.com/nagadomi/nunif/assets/5192788/c5f012f7-91c4-4690-a83b-647f402f9e3a)

**Test settings:**

- Model Type: art
- scale: 2
- noise_level: 3
- method: noise_scale

File Directory (I copy nunif & waifu2x to my main dir, imports weren't working right unless I did this)
![image](https://github.com/nagadomi/nunif/assets/5192788/a96faf24-ec1a-4f9d-a0f8-23072081e50a)

So all the code below comes from generation.py


```
imports...
from waifu2x.hub import waifu2x

# many defs

# pipe is just my diffusion pipeline, I use it to get which gpu is in use since I have many running
# settings is just a dict of settings I get from my frontend application using angular/node.js
def load_waifu2x(pipe, settings):
    global model_type
    global waifu2x_model
    waifu2x_settings = settings.get("plugins", {}).get("waifu2x", {"enabled": False})
    gpu_id = int(str(pipe.device)[-1])
    model_type = waifu2x_settings.get("model_type", "art")
    print(f"Loading Waifu2x model: {model_type} on GPU: {gpu_id}")
    waifu2x_model = waifu2x(
        model_type=model_type,
        method=None,
        noise_level=3,
        device_ids=[gpu_id],
        tile_size=256,
        keep_alpha=True,
        amp=False,
    )
    return waifu2x_model


# Just how I'm converting the method selection from the frontend
def waifu2x_method(noise_level, scale):
    if noise_level < 0 and scale <= 1:
        return None
    if noise_level >= 0 and scale <= 1:
        return "noise"
    if noise_level < 0 and scale == 2:
        return "scale"
    if noise_level >= 0 and scale == 2:
        return "noise_scale"
    if noise_level < 0 and scale == 4:
        return "scale4x"
    if noise_level >= 0 and scale == 4:
        return "noise_scale4x"


# Supposed to do the denoising and waifu2x upscaling
def waifu2x_upscaler(settings, image):
    global model_type
    global waifu2x_model
    waifu2x_settings = settings.get("plugins", {}).get("waifu2x", {"enabled": False})
    if settings["plugins"]["waifu2x"]["enabled"] is True:
        noise_level = waifu2x_settings.get("noise_level", 3)  # -1, 0, 1, 2, 3
        scale = waifu2x_settings.get("scale", 1)
        method = waifu2x_method(noise_level, scale)
        
        # Just saving settings so I can store in db later
        settings["plugins"]["waifu2x"]["method"] = method
        settings["plugins"]["waifu2x"]["model_type"] = model_type
        print(f"Waifu2x Upscaling image with method:{method} noise_level:{noise_level} scale:{scale}x...")
        
        # set model and infer
        waifu2x_model.set_mode(method, noise_level)
        return waifu2x_model.infer(image, output_type="pil")
```

When the application starts, a create method is called to setup and load the diffusion model and put waifu2x into memory. Then via a socket connection, create is called which does the following.

```
def shibiko_create(pipe, settings: dict, clip_layers, profile=False):
    print("Shibiko Create")
    settings = settings or {}
    lora_containers = []

    try:
        with torch.inference_mode(mode=True):
            load_scheduler(pipe, settings)

            # with torch.device(str(pipe.device)):
            load_loras(pipe, settings, lora_containers)
            load_clip_skip(pipe, settings["image"]["clip_skip"], clip_layers)

            image = create_image(pipe, settings, profile=profile)
            image = apply_lut(settings, image)
            image = waifu2x_upscaler(settings, image)
            
            # next two lines aren't used during this generation, the upscaler here is edsr
            image = upscaler(pipe, settings, image)
            image = remove_background(settings, image)
            
            image, filters = use_filters(image)
            settings["image"]["filters"] = filters
            settings["pipeline"]["device"] = str(pipe.device)

            # probably not needed
            image = image.convert("RGBA")

            remove_loras(pipe, lora_containers)
            torch.cuda.empty_cache()

            print(f"profile={profile}")
            return save(
                image,
                settings,
                preview=profile is not True,
                output=profile is not True,
                profile=profile
            )
    except Exception as e:
        print("Error generating shibiko image")
        print(e)
        traceback.print_exc()
        remove_loras(pipe, lora_containers)
        torch.cuda.empty_cache()
        return "Error generating image"
```

Other things to note. I didn't install any additional pip packages. When I ran it I didn't get any errors about a missing module or package. So I assumed I already had packages it needed installed. Though if there are any packages you believe are critical, I'll install them.


So when I generate I get this:
![2023-11-16_15-21-49](https://github.com/nagadomi/nunif/assets/5192788/059fd2d8-0577-43a5-a537-abd7005ce08b)

Which is blurry than the waifu2x website with the same settings:
![2023-11-16_13-15-47_waifu2x_art_noise3_scale](https://github.com/nagadomi/nunif/assets/5192788/2a8c91ff-31f6-4f61-896f-f35cdc2f112f)

**Comment by JemiloII** [comment] 2023-11-17 05:47
i tried the torch.hub.load method as well. same output, but it looks like with torch.hub.load, I don't need to fetch the entire repo manually. I tried with master & dev. Same result. The noise is removed but it is a little blurry compared to waifu2x website.

**Comment by JemiloII** [comment] 2023-11-17 05:50
oh, i figured it out. it was actually dumb mistake on my end. I was sharpening the image after using waifu2x where when I had the waifu2x website, i had sharpened the image before. Legit.

**Comment by JemiloII** [comment] 2023-11-17 10:34
So I run into a different issue now even if I set `amp=False`. So I was putting it all together and the following line I need creates an issue with waifu2x:

`torch.set_default_dtype(torch.float16)`


error:
```
Error generating shibiko image
"replication_pad2d" not implemented for 'Half'
Traceback (most recent call last):
  File "D:\diffusion\generation.py", line 806, in shibiko_create
    image = waifu2x(settings, image)
  File "D:\diffusion\generation.py", line 681, in waifu2x
    image = waifu2x_model.infer(image, method=method, noise_level=noise_level, o
utput_type="pil")
  File "C:\Users\Shibiko/.cache\torch\hub\nagadomi_nunif_dev\waifu2x\hub.py", li
ne 117, in infer
    return self.infer_pil(x, tta=tta, output_type=output_type, **kwargs)
  File "C:\Users\Shibiko/.cache\torch\hub\nagadomi_nunif_dev\waifu2x\hub.py", li
ne 95, in infer_pil
    return self.infer_tensor(rgb, alpha, tta=tta, output_type=output_type, **kwa
rgs)
  File "C:\Users\Shibiko/.cache\torch\hub\nagadomi_nunif_dev\waifu2x\hub.py", li
ne 104, in infer_tensor
    rgb, alpha = self.ctx.convert(
  File "C:\Users\Shibiko/.cache\torch\hub\nagadomi_nunif_dev\waifu2x\utils.py",
line 252, in convert
    rgb = self.render(x, method, noise_level, tile_size, batch_size, enable_amp)
  File "C:\Users\Shibiko/.cache\torch\hub\nagadomi_nunif_dev\waifu2x\utils.py",
line 208, in render
    z = tiled_render(x, self.noise_models[noise_level],
  File "C:\Users\Shibiko/.cache\torch\hub\nagadomi_nunif_dev\nunif\utils\render.
py", line 9, in tiled_render
    return SeamBlending.tiled_render(
  File "C:\Users\Shibiko/.cache\torch\hub\nagadomi_nunif_dev\nunif\utils\seam_bl
ending.py", line 70, in tiled_render
    x = F.pad(x.unsqueeze(0), seam_blending.pad, mode='replicate')[0]
RuntimeError: "replication_pad2d" not implemented for 'Half'
Removing Loras
Generation Timestamp or Error: Error generating image
Sending error response
Traceback (most recent call last):
  File "D:\diffusion\main.py", line 106, in <module>
    asyncio.run(main())
  File "C:\Users\Shibiko\AppData\Local\Programs\Python\Python310\lib\asyncio\run
ners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Shibiko\AppData\Local\Programs\Python\Python310\lib\asyncio\bas
e_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Shibiko\AppData\Local\Programs\Python\Python310\lib\asyncio\win
dows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Shibiko\AppData\Local\Programs\Python\Python310\lib\asyncio\bas
e_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Shibiko\AppData\Local\Programs\Python\Python310\lib\asyncio\bas
e_events.py", line 1868, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\Shibiko\AppData\Local\Programs\Python\Python310\lib\asyncio\win
dows_events.py", line 439, in select
    self._poll(timeout)
  File "C:\Users\Shibiko\AppData\Local\Programs\Python\Python310\lib\asyncio\win
dows_events.py", line 792, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt
```

**Comment by nagadomi** [comment] 2023-11-17 13:55
>RuntimeError: "replication_pad2d" not implemented for 'Half'

Maybe the input tensor is not loaded to CUDA device.
Transferring the input tensor to CUDA should resolve this error.
```
# x expects float16 RGB CPU tensor 
ret = model.infer(x.cuda())
```

**Comment by nagadomi** [comment] 2023-11-17 14:04
Also, waifu2x models have been trained with fp16, so there is generally no advantage to using fp32 (amp=False).
However, if the running device does not support fp16, fp32 can be used.

**Comment by nagadomi** [comment] 2023-11-17 14:14
>RuntimeError: "replication_pad2d" not implemented for 'Half'

Maybe this is related to the torchvision version.
I have confirmed that with torchvison==0.15.2 (torch==2.0.1) it works if the input tensor is cuda tensor as above example.

**Comment by JemiloII** [comment] 2023-11-18 00:16
I use the GPU to generate and I pass a PIL image as the source. I am using torch=2.1.0+cu121 though, so maybe it is torch. I currently have AMP set to False, but I don't think I notice a difference between the two.

**Comment by nagadomi** [comment] 2023-11-18 00:50
I did not use the above `cuda()` in my code, so I fixed it　https://github.com/nagadomi/nunif/commit/4b972f0be61f70a0a5e35e2f2e5a086c224aece9

----

I may have misunderstood your comment.
Do you mean that the error only occurs when `torch.set_default_dtype(torch.float16)` is used?

In torch 2.0.1, it could not be used due to an error in torchvision.
It is a bad practice to use `torch.set_default_dtype(torch.float16)`.
It may be needed in other codes such as stable diffusion, but in waifu2x, if you use `amp=True`, it will work with fp16 without changing the global settings.

**Comment by nagadomi** [comment] 2023-11-18 01:05
I added amp=True/False benchmark example. https://github.com/nagadomi/nunif/commit/86e13a084d7136aec4bda27357d5f52ce4e99d25

With 1200x1200 image, 
```
amp = True 0.7142 sec / image
amp = False 1.4027 sec / image
```

**Comment by nagadomi** [comment] 2023-11-18 21:45
I have added support for manual float16 input without amp=True.
`torch.set_default_dtype(torch.float16)` at model runtime should work with `model = model.half()`.
Note that `torch.set_default_dtype(torch.float16)` does not work when `torch.hub.load`.

 benchmark example
https://github.com/nagadomi/nunif/blob/02fef6f56837d2be119e4cf4ec2e955075fabb4b/waifu2x/hub.py#L276-L321


With 1200x1200 image,
```
amp=True 0.7145 sec / image
amp=False 1.4002 sec / image
amp=False half() 0.6021 sec / image
image_diff(amp=True, amp=False) tensor(0.)
image_diff(amp=True, amp=False half()) tensor(0.)
```

**Comment by JemiloII** [comment] 2023-11-19 06:00
@nagadomi You are awesome bro! I didn't know `torch.set_default_dtype(torch.float16)` was bad practice. I'll stop using it. Thanks for adding the half. So if I do `model.half()` will that use the gpu then? Is `model.cuda()` still needed?

**Comment by nagadomi** [comment] 2023-11-19 07:30
Both `cuda().half()` are needed.

Also, if loading code from this repo via torch.hub.load, you can use the following method (`force_reload=True` option) to force update to the latest source code.
```
torch.hub.help("nagadomi/nunif:master", "waifu2x", force_reload=True, trust_repo=True)
```
(Note that pre-trained models will also be re-downloaded)

**Closed** 2023-11-23 16:36 UTC
