### ISSUE TITLE
update.bat - error in the work log

### ISSUE THREAD

**Issue by cynodesmus** [nagadomi/nunif#189] opened 2024-07-24 15:47 UTC
Recently I decided to run an update script, and an error message appeared in the work log:
```
Download Models...
Traceback (most recent call last):
  File "runpy.py", line 187, in _run_module_as_main
  File "runpy.py", line 110, in _get_module_details
  File "D:\nunif\nunif\waifu2x\__init__.py", line 1, in <module>
    from .utils import Waifu2x
  File "D:\nunif\nunif\waifu2x\utils.py", line 3, in <module>
    import torch
  File "D:\nunif\python\lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module was not found. Error loading "D:\nunif\python\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
Error
```
File fbgemm.dll is present at the specified path. The error may be related to update "torch-2.4.0+cu118"

**Comment by nagadomi** [comment] 2024-07-24 16:06
Have you installed
"Microsoft Visual C++ Redistributable Packages" https://aka.ms/vs/16/release/vc_redist.x64.exe
?

**Comment by cynodesmus** [comment] 2024-07-24 17:22
I reinstalled VC++, but the problem persisted.
![vc](https://github.com/user-attachments/assets/b18321ef-997f-42e8-a5ba-9abd05bd52d4)
7 days ago, the update took place without errors. Today, after updating Torch from version 2.3.1 to version 2.4.0, this error appeared.

**Comment by nagadomi** [comment] 2024-07-24 17:22
I could not reproduce this error in my nunif-windows package environment.
However, a similar issue is posted in pytorch repo
https://github.com/pytorch/pytorch/issues/131662

**Comment by cynodesmus** [comment] 2024-07-24 17:40
In this case, I will return the old files from the backup. Probably a problem with pytorch. Should I close this incident?

**Comment by nagadomi** [comment] 2024-07-24 17:45
For now, You can revert to pytorch 2.3.1 with the following steps

1. run `nunif-prompt.bat` 
2. `python -m pip3 install torch==2.3.1 torchvision==0.8.2 --index-url https://download.pytorch.org/whl/cu118`

Note that if you run `update.bat`, the latest pytorch(2.4.0) will be installed again.

---
@cynodesmus 
No need to close this issue yet because it is possible that the same issue will be posted.

**Comment by cynodesmus** [comment] 2024-07-24 18:41
Oh, thank you. pytorch rollback to version 2.3.1 was successful.

**Comment by nagadomi** [comment] 2024-07-24 19:40
I have temporarily updated `requirements-torch.txt` to use torch==2.3.1 on Windows. 
I will revert this change when torch==2.4.1 is released.

**Closed** 2024-09-17 03:32 UTC
