### ISSUE TITLE
[Request] Add ability to save generated maps to a folder and reuse for a second run

### ISSUE THREAD

**Issue by wcapes** [nagadomi/nunif#97] opened 2024-03-27 05:35 UTC
I'd like to save the DepthMap images used to another folder on the first run, so if I do another run I can use the pre-generated maps instead of re-generating for a 2nd/3rd run.

This way makes it easier and faster to test different options available

**Comment by wcapes** [comment] 2024-03-27 17:36
The main slow down is the generation of the depth map and if we can cache/save/store that it can save HOURS when you taking the source image and loading the depth map to create the SBS final image.

I do believe this will be a HUGE bonus to this awesome software.

Thank you for considering it

**Comment by nagadomi** [comment] 2024-03-27 18:01
My recommended workflow for testing or previewing is Max FPS=0.25.
Ideally, processing time is reduced to 1/120 (for 30fps video).
I think it is a much better approach than this request.
A disadvantage is that seek does not work in some video players.

**Comment by wcapes** [comment] 2024-03-27 18:47
Would you consider then for the CLI tool?   I had a look at the code and adding this support to the feature where it reads the images from a folder could be the starting point maybe?

--input <Folder with Images>
--output <Folder for SBS Images>
--maps <Folder for Maps to be stored> OPTIONAL

Then when looping through the source images, it could load from MAPS folder if it exists and then do the SBS image
Guys could then test this out, and potentially if you wanted to do a movie, or episode, you could extract the frames - try different settings to get the best - and then just rebuild the video file ( This would be manual by the user usin FFMPEG )

Just thinking of ways to make it quicker for users.

If this works, could then investigate approaches for video.   I would be happy to test

**Comment by nagadomi** [comment] 2024-03-27 19:06
For now, I am planning to develop two CLI. exrpot depth and generate video from depth,frame,audio.

Also here is a benchmark.  I think depth estimation is much faster than you think. It is faster than saving and loading an image.
```python
import os
import torch
import PIL
import torchvision.transforms.functional as TF
import time


def bench_any():
    model = torch.hub.load("nagadomi/Depth-Anything_iw3", "DepthAnything",
                           encoder="vitb", # Any_B
                           trust_repo=True).cuda()
    RES = 392 # default resolution in iw3, 518 is also supported
    BATCH = 4
    N = 25
    x = torch.rand((BATCH, 3, RES, RES)).cuda() - 0.5
    with torch.inference_mode(), torch.autocast(device_type="cuda"):
        start = time.perf_counter()
        for i in range(N):
            depth = model(x)
        torch.cuda.synchronize()
        print(f"depth inference time per image: {round((time.perf_counter() - start) / (N * BATCH), 4)}s")


def bench_png():
    OUTPUT_DIR = "png_bench"
    FRAME_RES = (1920, 1080)  # consider frame images
    img = torch.rand((3, *FRAME_RES))
    img = TF.to_pil_image(img)
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    start = time.perf_counter()
    N = 100
    for i in range(N):
        file_path = os.path.join(OUTPUT_DIR, f"{i}.png")
        img.save(file_path)
        PIL.Image.open(file_path).load()
    print(f"PNG encode/save/load/decode time per image: {round((time.perf_counter() - start) / N, 4)}s")


if __name__ == '__main__':
    bench_any()
    bench_png()

```
result (Linux, RTX 3070ti)
```
depth inference time per image: 0.0144s
PNG encode/save/load/decode time per image: 0.2109s
```
result with FRAME_RES=(392,392)
```
depth inference time per image: 0.0144s
PNG encode/save/load/decode time per image: 0.0159s
```

**Comment by wcapes** [comment] 2024-03-27 19:19
Will check this out tomorrow (night here) thanks for the share :)

**Comment by nagadomi** [comment] 2024-03-28 06:05
I chose to simply add --export option to the existing iw3.cli. It can be used in GUI.
The input for video generation is a YAML config file. It will be generated when exporting. It also can be created manually.
The config file can define, folder path for frame images, folder path for depth images, audio file path, FPS, and etc.

**Comment by wcapes** [comment] 2024-03-28 08:08
Sounds like a plan, can't wait to check it out :)

ps: Wouldn't nag for features if we didn't think this is GREAT piece of software :)

**Comment by nagadomi** [comment] 2024-03-29 15:15
I haven't tested this much, so if something strange happens, it's most likely a bug.

**Comment by wcapes** [comment] 2024-03-30 07:25
This is amazing, thank you - will start testing and playing this weekend

**Comment by nagadomi** [comment] 2024-03-30 09:10
link to https://github.com/nagadomi/nunif/discussions/87


----
>Export started on frame 2, not 1

The number in the filename is frame PTS. No problem if filenames are in frame order.

Other problems do not happen in my env.
Is the normal Full SBS video generation feature working?
I am guessing that it is either the video you are using for testing or your python venv that is the cause.

**Comment by wcapes** [comment] 2024-03-30 09:25
Running part 2 after the first part 
command line used: python -m iw3.cli -i e:\dp1\dp1\iw3_export.yml -o e:\dp1\dp1\frames\ --yes --max-workers 8

![image](https://github.com/nagadomi/nunif/assets/88830951/6d08a915-be50-454b-bfa9-393aa34bf181)


If I use the GUI app it seems to work it's fine, I'm going to test your changes using the GUI and get back to you

**Comment by wcapes** [comment] 2024-03-30 09:44
Firstly I must say thank you for the continued assistance here :)

Using GUI on a different video file, a youtube video 1080p MP4, getting the same with the DEPTH folder where the images are legit PNG but empty and the RGB folder is spot on.

Can you think of anything I might have broken in my environment as I used the MASTER.ZIP download from here on a new setup?    Not sure what else I can do to help you

**Comment by nagadomi** [comment] 2024-03-30 09:49
>Also I used "Installer for Windows.bat" and "Open Prompt.bat" to update and get command line access

On windows, I have only checked nunif-windows-package.
https://github.com/nagadomi/nunif/blob/master/windows_package/docs/README.md
I recommend using this.

if you don't want to use it, let me know your Python environment.
Anaconda or official Python?
Also try updating pip packages.
```
python -m pip install --no-cache-dir --upgrade pip
python -m pip install --no-cache-dir --upgrade -r requirements-torch.txt
python -m pip install --no-cache-dir --upgrade -r requirements.txt
python -m pip install --no-cache-dir --upgrade -r requirements-gui.txt
```

>OverflowError

This is a ffmpeg problem that occurs with floating point FPS.
What is the fps value in iw3_export.yml?

**Comment by wcapes** [comment] 2024-03-30 11:20
Seem to be good now :)
Will continue testing

**Comment by nagadomi** [comment] 2024-03-31 03:56
`OverflowError: Python int too large to convert to C long` is now fixed in https://github.com/nagadomi/nunif/discussions/105

**Comment by nagadomi** [comment] 2024-04-22 11:11
If you find a problem, post a new issue.

**Closed by nagadomi** 2024-04-22 11:11 UTC
